apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: lab-admin
type: Opaque
stringData:
  POSTGRES_DB: symfony
  POSTGRES_USER: symfony
  POSTGRES_PASSWORD: lab-symfony
  DATABASE_URL: postgresql://symfony:lab-symfony@postgres:5432/symfony?serverVersion=16&charset=utf8
  APP_SECRET: lab-only-change-me
