# syntax=docker/dockerfile:1
FROM alpine:3.20
RUN --mount=type=secret,id=demo_secret \
    test -s /run/secrets/demo_secret \
    && echo "Secret disponível apenas durante esta instrução RUN" >/message.txt
CMD ["cat", "/message.txt"]
