apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  # Headless Service: não cria um ClusterIP virtual e é usado pelo StatefulSet
  # para identidade e descoberta de rede estáveis.
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
