apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Todos os recursos namespaced da base são aplicados em s78-lab.
namespace: s78-lab
resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - deployment.yaml
  - service.yaml
