apiVersion: v1
kind: Service
metadata:
  name: symfony-demo
spec:
  type: ClusterIP
  selector:
    # Esta label tem de coincidir com a label dos Pods Symfony.
    # O incidente 2 quebra deliberadamente esta relação.
    app: symfony-demo
  ports:
    - name: http
      port: 80
      # O nome `http` corresponde à porta nomeada no container.
      targetPort: http
      protocol: TCP
