apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: symfony-demo
spec:
  ingressClassName: traefik
  rules:
    - host: symfony-ingress.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: symfony-demo
                port:
                  number: 80
